version: "3"
services:
  dependencies:
    container_name: media-viewer-dev-node
    image: "node:20"
    working_dir: /home/node/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
    volumes:
      - ./home-media-viewer:/home/node/app
    networks:
      - home-media-dev-network

  db:
    container_name: media-viewer-dev-db
    hostname: media-viewer-dev-db
    image: "mariadb:11"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    ports:
      - ${MARIADB_PORT_ON_HOST}:3306
    volumes:
      - home-media-dev-db:/var/lib/mysql
    networks:
      - home-media-dev-network
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 800m

  app:
    container_name: media-viewer-dev-app
    hostname: media-viewer-dev-app
    build:
      dockerfile: ./docker/dev/app/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      APP_ALBUM_ROOT_PATH: ${APP_ALBUM_ROOT_PATH}
      DATABASE_URL: ${DATABASE_URL}
      LONG_PROCESS_TIMEOUT_SEC: ${LONG_PROCESS_TIMEOUT_SEC}
      PROCESS_TOKEN: ${PROCESS_TOKEN}
      TS_NODE_PROJECT: /home/node/app/tsconfig.json
      APP_SESSION_SECRET: ${APP_SESSION_SECRET}
      HOSTNAME: ${HOSTNAME}
      IS_BACKGROUND_PROCESS_ENABLED: ${IS_BACKGROUND_PROCESS_ENABLED}
    volumes:
      - ./home-media-viewer:/home/node/app
      - ./static:${APP_ALBUM_ROOT_PATH}
    #  - ./test/files:${APP_ALBUM_ROOT_PATH}
      - home-media-dev-storage:${APP_STORAGE_PATH}
    ports:
      - ${WEB_PORT}:3000
    networks:
      - home-media-dev-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 800m

  testrunner:
    container_name: media-viewer-dev-testrunner
    hostname: media-viewer-dev-testrunner
    build:
      dockerfile: ./docker/dev/testrunner/Dockerfile
      context: .
      target: testrunner
    depends_on:
      - app
    environment:
      APP_ALBUM_ROOT_PATH: ${APP_ALBUM_ROOT_PATH}
      DATABASE_URL: ${DATABASE_URL}
      LONG_PROCESS_TIMEOUT_SEC: ${LONG_PROCESS_TIMEOUT_SEC}
      APP_SESSION_SECRET: ${APP_SESSION_SECRET}
      PROCESS_TOKEN: ${PROCESS_TOKEN}
      TS_NODE_PROJECT: /home/node/app/tsconfig.json
      APP_URL: http://media-viewer-dev-app:3000
    volumes:
      - ./home-media-viewer:/home/node/app
    networks:
      - home-media-dev-network

networks:
  home-media-dev-network:

volumes:
  home-media-dev-storage:

  home-media-dev-db:
