import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { File } from 'buffer'
import FileList from '@/components/fileList'
import PageHeader from '@/components/layout/pageHeader'
import LayoutLoggedIn from '@/components/layout/layoutLoggedIn'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LayoutLoggedIn>
          <FileList />
        </LayoutLoggedIn>
      </main>
    </>
  )
}
